sudo: false
language: ruby
cache: bundler
#rvm:
#- 2.1
#- 2.1.1

rvm:
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - rbx-2
  - ruby-head
  - jruby-head
  - ree

install:
  # Install Jekyll and dependencies
  - bundle install

script: "bundle exec jekyll build"
#script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "QTUE02RNWZbPNSHOHxUub/QqCcr+faQlPhuQdfbU3l9GBBJ6STj/V4wdQbIQFfmb+9Ygu8ONT+h0xh7Wbc8b0u5glDmkyd6cgOQ3+FC9fPL3f9yePhNWDE++rn6Uf8flPUWDn58r5TJ48u36D33k3tHYFEZRgy0XmSfloiYAc4+RMGTB8Zo+lGqOiztoXiTR5u7thA4MZz5UgUk+yMEQf3nmFNPGiL9EgEDzh7ybhjjuNXGi/yLyoFaUbkgypYQO6WoIBOIZyAf8sKiMdjaps8xeK1zOY+oyXcGHLlqcf7SbzKQtN+MNmZJ2PvcCOQoU7/Ms0hsUqtUxLrhhC8GuhDUMfhTRgo6ZKC4yncBNFxqzu3zDApgHdvnUg+HlzOQ/ks4ZhqqR9VdvI9pCJcMaPN34rdwRlq4i/CBgpLS1JdfbM2dQXTxy5wCbvouMARCCUKsjvWhOe1Hbawupe5ncSTHsiCHK2ba9lSfgIirHfUGjnkjHgd21xFxJ4PiP/ro0/6oz+NR2GK/rQT8eH6/JiQ6SrSRRKJNM00RjPzfd5B3c7hLuWPRHYArW/hMhZPbr34uoZKSYo56h4iKL9wxdRjbOcEFu5DLyrgKUMaoaVDEOaff+RcStavCij/T8YPZzJa8Vv3aKqVFKe2lCe3KGhW6uvvxrc/yOqCjzZV5cZO8="
branches:
  only:
    - master

