name: PyeongHo 
description: factory
meta_description: "factory"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://pyeongho.github.io/'
google_analytics: 'UA-90332203-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://pyeongho.github.io/'
author:         'PyeongHo'


collections:
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: tags
    values:
      layout: tag
