name: PyeongHo Site
description: lab lab lab
meta_description: "lab"

markdown: redcarpet
highlighter: rouge
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
extensions: [fenced_code_blocks]
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'
