# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ruby:2.4.0

pipelines:  
  default:
    - step:
        script:
          - git config --global user.email "pyeongho@bitbucket.com"
          - git config --global user.name "pyeongho"
          - gem install jekyll
          - bundle install
          - rm -rf .git
          - git clone https://pyeongho:$SITE_A@github.com/pyeongho/pyeongho.github.io.git _site
          - jekyll build --incremental
          - cd _site
          - git add . && git commit -m "New version - $BITBUCKET_COMMIT"
          - git push origin master
          